# Första uppgiften

In [2]:
import pandas as pd
regression_data = {"inkomst (y)": [58500, 42000, 34000, 39000], "Ålder (x)": [58, 29, 35, 42]}
df_reg = pd.DataFrame(regression_data)
df_reg

   inkomst (y)  Ålder (x)
0        58500         58
1        42000         29
2        34000         35
3        39000         42

Andra

In [3]:
classification_data = {"Kön (y)": ["Man", "Kvinna", "Man", "Kvinna"], "Inkomst(x1)": [84000, 36750, 33000, 53000], "Ålder(x2)": [58, 29, 35, 42]}
df_classification = pd.DataFrame(classification_data)
df_classification

  Kön (y)  Inkomst(x1)  Ålder(x2)
0     Man        84000         58
1  Kvinna        36750         29
2     Man        33000         35
3  Kvinna        53000         42

In [4]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

diabetes = load_diabetes(as_frame=True)

df=diabetes.frame
print(df.head())

X = df.drop(columns='target')
y = df['target']

X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.25, random_state=42)

        age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142

         s4        s5        s6  target
0 -0.002592  0.019907 -0.017646   151.0
1 -0.039493 -0.068332 -0.092204    75.0
2 -0.002592  0.002861 -0.025930   141.0
3  0.034309  0.022688 -0.009362   206.0
4 -0.002592 -0.031988 -0.046641   135.0

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import root_mean_squared_error

# 1. Träna två modeller på träningsdatan
linreg = LinearRegression()
tree = DecisionTreeRegressor(random_state=42)

linreg.fit(X_train, y_train)
tree.fit(X_train, y_train)

# 2. Utvärdera modellerna på valideringsdatan och välj den bäst presterande
rmse_linreg = root_mean_squared_error(y_val, linreg.predict(X_val))
rmse_tree = root_mean_squared_error(y_val, tree.predict(X_val))

print(f"RMSE på validering - Linjär Regression: {rmse_linreg: .2f}")
print(f"RMSE på validering - Beslutsträd: {rmse_tree: .2f}")

# Välj den bäst presterande modellen på valideringsdatan. Den modellen som har lägre RMSE är bättre.
if rmse_linreg < rmse_tree:
    best_model = LinearRegression()
    best_model_name = "Linjär Regression"
else:
    best_model = DecisionTreeRegressor(random_state=42)
    best_model_name = "Beslutsträd"
    
# 3. Om prestationen är bra nog, träna om den bäst presterande modellen på träningsdatan och valideringsdatan ihopslagen innan den utvärderas på testdatan.

best_model.fit(X_train_full, y_train_full)

# Utvärdera modellen på testdatan.
rmse_test = root_mean_squared_error(y_test, best_model.predict(X_test))

print(f"Bästa modell baserat på validering: {best_model_name}")
print(f"RMSE på testdatan: {rmse_test: .2f}")

# 4. Träna om modellen på hela datasetet innan vi börjar använda den skarpt.
best_model.fit(X, y)

RMSE på validering - Linjär Regression:  51.19
RMSE på validering - Beslutsträd:  65.81
Bästa modell baserat på validering: Linjär Regression
RMSE på testdatan:  53.85

LinearRegression()

## K-delad korsvalidering

In [11]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import LinearSVR
from sklearn.model_selection import cross_validate

X, y = load_diabetes(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr = LinearRegression()
svm = LinearSVR()

cv_lr = cross_validate(lr, X, y, cv=5, scoring = 'neg_root_mean_squared_error')
cv_svm = cross_validate(svm, X, y, cv=3, scoring = 'neg_root_mean_squared_error')

print(cv_lr.keys())
print(cv_lr['test_score'])
print(cv_svm['test_score'])

if np.mean(cv_lr['test_score']) > np.mean(cv_svm['test_score']):
    print("The best model is linear regression.")
elif np.mean(cv_lr['test_score']) == np.mean(cv_svm['test_score']):
    print("The models are equally good.")
else:
    print("The best model is support vector machine.")

dict_keys(['fit_time', 'score_time', 'test_score'])
[-52.72497937 -55.03486476 -56.90068179 -54.85204179 -53.94638716]
[-90.2051448  -93.11971338 -94.32208488]
The best model is linear regression.

### RMSE och Hyperparametrar

In [12]:
from sklearn.metrics import root_mean_squared_error
y_true = [4, 10, 8]
y_pred = [2, 13, 5]
root_mean_squared_error(y_true, y_pred)

2.70801280154532

In [13]:
from sklearn.linear_model import LinearRegression

# Data
example_data = {"y": [-10, 3, 2, 7, -9, 10, 9, 7, 4, 7, 3, 2, -4, -5, -9, -4], "x": [-3,0,1,2,4,2,3,5,7,8,9,6,-2,-5,-1,-2]}
example_data = pd.DataFrame(example_data)

lin_reg_1 = LinearRegression(fit_intercept=False)
lin_reg_1.fit(example_data[["x"]], example_data["y"])

lin_reg_2 = LinearRegression(fit_intercept=True)
lin_reg_2.fit(example_data[["x"]], example_data["y"])

print('Parameters for lin_reg_1.', 'Intercept:', round(lin_reg_1.intercept_, 2), 'Slope', round(lin_reg_1.coef_[0], 2))
print('Parameters for lin_reg_2.', 'Intercept:', round(lin_reg_2.intercept_, 2), 'Slope', round(lin_reg_2.coef_[0], 2))

Parameters for lin_reg_1. Intercept: 0.0 Slope 0.8
Parameters for lin_reg_2. Intercept: -1.13 Slope 0.91

# Gridsearch

In [ ]:
from sklearn.model_selection import GridSearchCV
model = LinearRegression()

hyperparameters = {'fit_intercept': [True, False]}

grid_search = GridSearchCV(estimator=model, param_grid = hyperparameters, scoring='neg_mean_squared_error', cv=2)

grid_search.fit(example_data[["x"]], example_data["y"])

GridSearchCV(cv=2, estimator=LinearRegression(),
             param_grid={'fit_intercept': [True, False]},
             scoring='neg_mean_squared_error')

In [19]:
df_gs_results = pd.DataFrame(grid_search.cv_results_)
df_gs_results.iloc[:, [0,1,5]]
df_gs_results.iloc[:, [5,6,7,8]]
df_gs_results.iloc[:, [5,8,10]]
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_fit_intercept,params,split0_test_score,split1_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001252,0.000275,0.001327,0.000341,True,{'fit_intercept': True},-59.095576,-28.876354,-43.985965,15.109611,2
1,0.000910,0.000047,0.000689,0.000056,False,{'fit_intercept': False},-47.703118,-28.890138,-38.296628,9.406490,1

In [22]:
from sklearn.model_selection import GridSearchCV

model = LinearRegression()

hyperparameters = {'fit_intercept': [True, False]}

grid_search = GridSearchCV(estimator=model, param_grid=hyperparameters, scoring='neg_mean_squared_error', cv=3)

grid_search.fit(example_data[["x"]], example_data["y"])

grid_search.predict([[6]])

c:\Users\mansk\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([4.78915663])

In [23]:
print("Best Hyperparameters from GridSearchCV:", grid_search.best_params_)
print("Best Cross-Validation MSE:", -grid_search.best_score_)

best_model = grid_search.best_estimator_
print(f"Best Model Coefficients. Intercept: {round(best_model.intercept_, 2)}, Slope: {round(best_model.coef_[0], 2)}")

Best Hyperparameters from GridSearchCV: {'fit_intercept': False}
Best Cross-Validation MSE: 28.554233641184407
Best Model Coefficients. Intercept: 0.0, Slope: 0.8

# Kategorisk data

In [24]:
nominal_data = {'färg': ['röd', 'grön', 'blå', 'svart', 'röd', 'grön', 'grön', 'röd']}
nominal_df = pd.DataFrame(nominal_data)
nominal_df

    färg
0    röd
1   grön
2    blå
3  svart
4    röd
5   grön
6   grön
7    röd

In [25]:
oh_encoding = pd.get_dummies(nominal_df, dtype= int)
oh_encoding

   färg_blå  färg_grön  färg_röd  färg_svart
0         0          0         1           0
1         0          1         0           0
2         1          0         0           0
3         0          0         0           1
4         0          0         1           0
5         0          1         0           0
6         0          1         0           0
7         0          0         1           0

In [26]:
dummy_encoding = pd.get_dummies(nominal_df, dtype=int, drop_first= True)
dummy_encoding

   färg_grön  färg_röd  färg_svart
0          0         1           0
1          1         0           0
2          0         0           0
3          0         0           1
4          0         1           0
5          1         0           0
6          1         0           0
7          0         1           0

In [27]:
ordinal_data = {'Produkt': ['XXX', 'YYY', 'XXY', 'XYX', 'YXX'], 'Pris': ['hög', 'medel', 'låg', 'hög', 'låg']}
ordinal_df = pd.DataFrame(ordinal_data)
ordinal_df

  Produkt   Pris
0     XXX    hög
1     YYY  medel
2     XXY    låg
3     XYX    hög
4     YXX    låg

In [28]:
mapping = {"låg": 1, "medel": 2, "hög": 3}
ordinal_df["Pris"] = ordinal_df["Pris"].map(mapping)
ordinal_df

  Produkt  Pris
0     XXX     3
1     YYY     2
2     XXY     1
3     XYX     3
4     YXX     1

In [29]:
ordinal_df_2 = pd.DataFrame(ordinal_data)

ordinal_df_2['PrisOrdinalKodad'] = ordinal_df_2['Pris'].map(mapping)
ordinal_df_2

  Produkt   Pris  PrisOrdinalKodad
0     XXX    hög                 3
1     YYY  medel                 2
2     XXY    låg                 1
3     XYX    hög                 3
4     YXX    låg                 1

In [30]:
nominal_df

    färg
0    röd
1   grön
2    blå
3  svart
4    röd
5   grön
6   grön
7    röd

In [31]:
from sklearn.preprocessing import OneHotEncoder
OneHotEncoder(sparse_output=False).fit_transform(nominal_df[['färg']])

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [32]:
example_data = {'pris (tkr)': [4200, 2500, 7900, 6100, 6500], 'kvm': [120, 80, 250, 200, 150], 'antal rum': [4,3,7,5,4], 'byggår': [2005,2016,1980,1990,2020]}
example_data = pd.DataFrame(example_data)
example_data

   pris (tkr)  kvm  antal rum  byggår
0        4200  120          4    2005
1        2500   80          3    2016
2        7900  250          7    1980
3        6100  200          5    1990
4        6500  150          4    2020

In [33]:
example_data['snitt_kvm_per_rum'] = example_data['kvm'] / example_data['antal rum']

example_data['ny_husmodell'] = (example_data['byggår'] > 2000).astype(int)

example_data

   pris (tkr)  kvm  antal rum  byggår  snitt_kvm_per_rum  ny_husmodell
0        4200  120          4    2005          30.000000             1
1        2500   80          3    2016          26.666667             1
2        7900  250          7    1980          35.714286             0
3        6100  200          5    1990          40.000000             0
4        6500  150          4    2020          37.500000             1

In [34]:
from sklearn.preprocessing import StandardScaler
import numpy as np

example_data = np.array([[1.0,2.0], [3.0, 6.0], [5.0,10.0]])

scaler = StandardScaler()
example_data_scaled = scaler.fit_transform(example_data)

print("Original data:\n", example_data)
print("Scaled data:\n", example_data_scaled)
print("Medelvärde efter skalning:", np.mean(example_data_scaled, axis=0))
print("Standardavvikelse efter skalning:", np.std(example_data_scaled, axis=0))

Original data:
 [[ 1.  2.]
 [ 3.  6.]
 [ 5. 10.]]
Scaled data:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
Medelvärde efter skalning: [0. 0.]
Standardavvikelse efter skalning: [1. 1.]